name: CI & CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.9"

      - name: Install cibuildwheel
        run: pip install cibuildwheel poetry --pre

      - name: Build wheels
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_BEFORE_ALL: >
            cd pylibpostal/libpostal && 
            ./bootstrap.sh && 
            ./configure && 
            make && 
            make install && 
            ldconfig && 
            pkg-config --cflags libpostal && 
            pkg-config --libs libpostal && 
            pkg-config --cflags --libs libpostal
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1

      - name: Deploy wheels
        run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PW }}
